import uuid
from datetime import UTC, datetime

from pydantic import BaseModel, Field

from backend.intelligence.recovery.actions import ActionRiskLevel, RecoveryActionType


class RecoveryStep(BaseModel):
    """A single deterministic action within a broader recovery plan."""

    step_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for this recovery step.",
    )
    action_type: RecoveryActionType = Field(
        description="The strictly bounded action to perform.",
    )
    target_component: str = Field(
        description="The component ID this action targets (e.g. 'sim-api'). Must exist in the graph.",
    )
    justification: str = Field(
        description="Why this specific action is being taken for this component.",
    )
    estimated_risk: ActionRiskLevel = Field(
        description="The estimated risk level for this specific step.",
    )


class RecoveryPlan(BaseModel):
    """A validated, structured plan designed to resolve an ongoing incident."""

    plan_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for the recovery plan.",
    )
    incident_id: str | None = Field(
        default=None,
        description="The ID of the incident this plan addresses, if known.",
    )
    steps: list[RecoveryStep] = Field(
        default_factory=list,
        description="The sequential list of actions to execute.",
    )
    overall_risk: ActionRiskLevel = Field(
        description="The highest risk level among all steps.",
    )
    impact_analysis: str = Field(
        description="AI explanation of the potential impact and side-effects of executing this plan.",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="When this plan was generated.",
    )

    # Internal fields not generated by the AI
    is_validated: bool = Field(
        default=False,
        description="Whether this plan has passed rigorous internal application validation.",
    )
