"""Add events and state_transitions schemas

Revision ID: c180750c1017
Revises: 007
Create Date: 2026-09-26 23:34:52.205807
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c180750c1017'
down_revision: str | None = '007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_correlation_id'), 'events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_service_id'), 'events', ['service_id'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_table('state_transitions',
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_transitions_new_status'), 'state_transitions', ['new_status'], unique=False)
    op.create_index(op.f('ix_state_transitions_service_id'), 'state_transitions', ['service_id'], unique=False)
    op.alter_column('actions', 'id',
               existing_type=sa.UUID(),
               comment='Unique record identifier',
               existing_nullable=False)
    op.alter_column('actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of record creation',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('actions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of last update',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('anomalies', 'incident_id',
               existing_type=sa.UUID(),
               comment='Associated incident (set when correlated)',
               existing_nullable=True)
    op.alter_column('anomalies', 'id',
               existing_type=sa.UUID(),
               comment='Unique record identifier',
               existing_nullable=False)
    op.alter_column('anomalies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of record creation',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('anomalies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of last update',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('experience_learning_signals_experience_id_key'), 'experience_learning_signals', type_='unique')
    op.drop_index(op.f('ix_els_action_type'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_els_environment'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_els_experience_id'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_els_incident_id'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_els_is_simulated'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_els_signal_type'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_els_source_fingerprint'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_els_target_component'), table_name='experience_learning_signals')
    op.create_index(op.f('ix_experience_learning_signals_action_type'), 'experience_learning_signals', ['action_type'], unique=False)
    op.create_index(op.f('ix_experience_learning_signals_environment'), 'experience_learning_signals', ['environment'], unique=False)
    op.create_index(op.f('ix_experience_learning_signals_experience_id'), 'experience_learning_signals', ['experience_id'], unique=True)
    op.create_index(op.f('ix_experience_learning_signals_incident_id'), 'experience_learning_signals', ['incident_id'], unique=False)
    op.create_index(op.f('ix_experience_learning_signals_is_simulated'), 'experience_learning_signals', ['is_simulated'], unique=False)
    op.create_index(op.f('ix_experience_learning_signals_signal_type'), 'experience_learning_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_experience_learning_signals_source_fingerprint'), 'experience_learning_signals', ['source_fingerprint'], unique=False)
    op.create_index(op.f('ix_experience_learning_signals_target_component'), 'experience_learning_signals', ['target_component'], unique=False)
    op.alter_column('incidents', 'id',
               existing_type=sa.UUID(),
               comment='Unique record identifier',
               existing_nullable=False)
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of record creation',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('incidents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of last update',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ok_action_type'), table_name='operational_knowledge')
    op.drop_index(op.f('ix_ok_environment'), table_name='operational_knowledge')
    op.drop_index(op.f('ix_ok_is_simulated'), table_name='operational_knowledge')
    op.drop_index(op.f('ix_ok_knowledge_id'), table_name='operational_knowledge')
    op.drop_index(op.f('ix_ok_target_component'), table_name='operational_knowledge')
    op.drop_constraint(op.f('operational_knowledge_knowledge_id_key'), 'operational_knowledge', type_='unique')
    op.create_index(op.f('ix_operational_knowledge_action_type'), 'operational_knowledge', ['action_type'], unique=False)
    op.create_index(op.f('ix_operational_knowledge_environment'), 'operational_knowledge', ['environment'], unique=False)
    op.create_index(op.f('ix_operational_knowledge_is_simulated'), 'operational_knowledge', ['is_simulated'], unique=False)
    op.create_index(op.f('ix_operational_knowledge_knowledge_id'), 'operational_knowledge', ['knowledge_id'], unique=True)
    op.create_index(op.f('ix_operational_knowledge_target_component'), 'operational_knowledge', ['target_component'], unique=False)
    op.alter_column('outcomes', 'id',
               existing_type=sa.UUID(),
               comment='Unique record identifier',
               existing_nullable=False)
    op.alter_column('outcomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of record creation',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('outcomes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of last update',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outcomes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of last update',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('outcomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of record creation',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('outcomes', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique record identifier',
               existing_nullable=False)
    op.drop_index(op.f('ix_operational_knowledge_target_component'), table_name='operational_knowledge')
    op.drop_index(op.f('ix_operational_knowledge_knowledge_id'), table_name='operational_knowledge')
    op.drop_index(op.f('ix_operational_knowledge_is_simulated'), table_name='operational_knowledge')
    op.drop_index(op.f('ix_operational_knowledge_environment'), table_name='operational_knowledge')
    op.drop_index(op.f('ix_operational_knowledge_action_type'), table_name='operational_knowledge')
    op.create_unique_constraint(op.f('operational_knowledge_knowledge_id_key'), 'operational_knowledge', ['knowledge_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_ok_target_component'), 'operational_knowledge', ['target_component'], unique=False)
    op.create_index(op.f('ix_ok_knowledge_id'), 'operational_knowledge', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_ok_is_simulated'), 'operational_knowledge', ['is_simulated'], unique=False)
    op.create_index(op.f('ix_ok_environment'), 'operational_knowledge', ['environment'], unique=False)
    op.create_index(op.f('ix_ok_action_type'), 'operational_knowledge', ['action_type'], unique=False)
    op.alter_column('incidents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of last update',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of record creation',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('incidents', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique record identifier',
               existing_nullable=False)
    op.drop_index(op.f('ix_experience_learning_signals_target_component'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_experience_learning_signals_source_fingerprint'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_experience_learning_signals_signal_type'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_experience_learning_signals_is_simulated'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_experience_learning_signals_incident_id'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_experience_learning_signals_experience_id'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_experience_learning_signals_environment'), table_name='experience_learning_signals')
    op.drop_index(op.f('ix_experience_learning_signals_action_type'), table_name='experience_learning_signals')
    op.create_index(op.f('ix_els_target_component'), 'experience_learning_signals', ['target_component'], unique=False)
    op.create_index(op.f('ix_els_source_fingerprint'), 'experience_learning_signals', ['source_fingerprint'], unique=False)
    op.create_index(op.f('ix_els_signal_type'), 'experience_learning_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_els_is_simulated'), 'experience_learning_signals', ['is_simulated'], unique=False)
    op.create_index(op.f('ix_els_incident_id'), 'experience_learning_signals', ['incident_id'], unique=False)
    op.create_index(op.f('ix_els_experience_id'), 'experience_learning_signals', ['experience_id'], unique=False)
    op.create_index(op.f('ix_els_environment'), 'experience_learning_signals', ['environment'], unique=False)
    op.create_index(op.f('ix_els_action_type'), 'experience_learning_signals', ['action_type'], unique=False)
    op.create_unique_constraint(op.f('experience_learning_signals_experience_id_key'), 'experience_learning_signals', ['experience_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('anomalies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of last update',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('anomalies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of record creation',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('anomalies', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique record identifier',
               existing_nullable=False)
    op.alter_column('anomalies', 'incident_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Associated incident (set when correlated)',
               existing_nullable=True)
    op.alter_column('actions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of last update',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of record creation',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('actions', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique record identifier',
               existing_nullable=False)
    op.drop_index(op.f('ix_state_transitions_service_id'), table_name='state_transitions')
    op.drop_index(op.f('ix_state_transitions_new_status'), table_name='state_transitions')
    op.drop_table('state_transitions')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_service_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_correlation_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
