"""
SynapseOps Domain Models — Action.

An Action represents a proposed or authorized recovery-related operation.

IMPORTANT SAFETY BOUNDARY:
This domain model represents the *description* of a recovery action.
It does not execute anything. It has no connection to shell commands,
Docker APIs, Kubernetes APIs, or any other execution mechanism.

The Action Executor (Phase 10) will receive authorized action instances
from the Policy Engine (Phase 9) and carry them out through a bounded,
validated execution layer.

This separation — between action representation and action execution —
is a core architectural safety principle established in Phase 0.
"""

from datetime import UTC, datetime
from enum import StrEnum
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class ActionType(StrEnum):
    """Enumeration of the action types that SynapseOps may eventually support.

    These types are defined conceptually at Phase 1.
    The concrete implementation of each type belongs to the Action Executor (Phase 10).
    The risk classification of each type belongs to the Policy Engine (Phase 9).
    """

    RESTART_SERVICE = "restart_service"
    SCALE_SERVICE = "scale_service"
    DRAIN_QUEUE = "drain_queue"
    ADJUST_RESOURCE_LIMIT = "adjust_resource_limit"
    REROUTE_TRAFFIC = "reroute_traffic"
    TRIGGER_ROLLBACK = "trigger_rollback"
    NOTIFY_OPERATOR = "notify_operator"  # Always safe; informational only
    NO_ACTION = "no_action"  # Explicit decision to not act (record reason)


class ActionRiskLevel(StrEnum):
    """Risk classification of a proposed action.

    These levels correspond to the action-risk hierarchy defined in SAFETY.md.
    The Policy Engine (Phase 9) will assign and enforce these levels.
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ActionStatus(StrEnum):
    """Lifecycle status of an action."""

    PROPOSED = "proposed"  # Generated by recovery planner; awaiting evaluation
    POLICY_APPROVED = "policy_approved"  # Cleared by policy engine for execution
    AWAITING_APPROVAL = "awaiting_approval"  # Queued for human authorization
    APPROVED = "approved"  # Human-authorized
    REJECTED = "rejected"  # Denied by policy or human operator
    EXECUTING = "executing"  # Currently being executed
    COMPLETED = "completed"  # Execution completed (success or failure)
    ROLLED_BACK = "rolled_back"  # Execution reversed via rollback


class Action(BaseModel):
    """Pydantic domain model representing a recovery action.

    Actions are generated by the Recovery Planner (Phase 8), evaluated by
    the Policy Engine (Phase 9), and executed by the Action Executor (Phase 10).

    At Phase 1, this model serves as the foundational domain representation.
    """

    id: UUID = Field(default_factory=uuid4, description="Unique action identifier")
    incident_id: UUID = Field(..., description="Incident this action addresses")
    action_type: ActionType = Field(..., description="Type of recovery operation")
    status: ActionStatus = Field(
        default=ActionStatus.PROPOSED,
        description="Current lifecycle status of the action",
    )
    risk_level: ActionRiskLevel = Field(
        ...,
        description="Risk classification assigned by the policy engine",
    )
    target_service: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Name of the service or resource this action targets",
    )
    parameters: dict[str, str | int | float | bool] = Field(
        default_factory=dict,
        description="Action-type-specific parameters (e.g., replicas=3 for scale_service)",
    )
    rationale: str | None = Field(
        default=None,
        description="Explanation of why this action was proposed",
    )
    rollback_description: str | None = Field(
        default=None,
        description="Description of how this action can be reversed if needed",
    )
    proposed_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="UTC timestamp when the action was proposed",
    )
    executed_at: datetime | None = Field(
        default=None,
        description="UTC timestamp when execution began",
    )

    model_config = {"from_attributes": True}
