'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api/client';
import { IncidentReasoningResult } from '@/lib/api/types';
import { Brain, FileText, CheckCircle2, Search, Target, AlertTriangle, Lightbulb } from 'lucide-react';
import Link from 'next/link';

export default function ReasoningPage() {
  const [reasoning, setReasoning] = useState<IncidentReasoningResult | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
      try {
        const data = await api.getIncidentReasoning();
        setReasoning(data);
      } catch (error) {
        console.error("Failed to load AI Reasoning", error);
      } finally {
        setLoading(false);
      }
    }
    
    fetchData();
  }, []);

  if (loading) {
    return (
      <div className="p-8 flex items-center justify-center min-h-screen">
        <div className="text-zinc-400 flex items-center gap-2">
          <Brain className="h-5 w-5 animate-pulse" />
          Analyzing recent incidents and topology...
        </div>
      </div>
    );
  }

  if (!reasoning) {
    return (
      <div className="p-8 max-w-7xl mx-auto space-y-6">
        <div className="p-8 text-center border border-zinc-800 border-dashed rounded-xl text-zinc-500">
          No recent reasoning data available or AI provider is unavailable.
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-white mb-2 flex items-center gap-3">
          <Brain className="h-8 w-8 text-purple-500" />
          AI Incident Reasoning
        </h1>
        <p className="text-zinc-400">Structured diagnosis generated by the AI reasoning engine.</p>
        <div className="mt-4 flex gap-4">
          <span className="px-3 py-1 bg-zinc-900 border border-zinc-800 rounded-md text-xs font-mono text-zinc-400">
            Provider: {reasoning.provider_name}
          </span>
          <span className="px-3 py-1 bg-zinc-900 border border-zinc-800 rounded-md text-xs font-mono text-zinc-400">
            Model: {reasoning.provider_model}
          </span>
          <span className="px-3 py-1 bg-zinc-900 border border-zinc-800 rounded-md text-xs font-mono text-zinc-400">
            Generated: {new Date(reasoning.timestamp).toLocaleString()}
          </span>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        {/* Left Column */}
        <div className="space-y-8">
          <div className="p-6 bg-zinc-900/50 border border-zinc-800 rounded-xl">
            <h2 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
              <FileText className="h-5 w-5 text-blue-400" /> Summary
            </h2>
            <p className="text-zinc-300 leading-relaxed">
              {reasoning.summary}
            </p>
          </div>

          <div className="p-6 bg-zinc-900/50 border border-zinc-800 rounded-xl space-y-4">
            <h2 className="text-lg font-semibold text-white flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-emerald-400" /> Ground Facts
            </h2>
            <ul className="space-y-2">
              {(reasoning.facts || []).map((fact, idx) => (
                <li key={idx} className="flex items-start gap-2 text-sm text-zinc-300">
                  <div className="min-w-1.5 h-1.5 rounded-full bg-emerald-500 mt-1.5" />
                  {fact}
                </li>
              ))}
            </ul>
          </div>

          <div className="p-6 bg-zinc-900/50 border border-zinc-800 rounded-xl space-y-4">
            <h2 className="text-lg font-semibold text-white flex items-center gap-2">
              <Search className="h-5 w-5 text-cyan-400" /> Observations
            </h2>
            <ul className="space-y-2">
              {(reasoning.observations || []).map((obs, idx) => (
                <li key={idx} className="flex items-start gap-2 text-sm text-zinc-300">
                  <div className="min-w-1.5 h-1.5 rounded-full bg-cyan-500 mt-1.5" />
                  {obs}
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Right Column */}
        <div className="space-y-8">
          <div className="p-6 bg-zinc-900/50 border border-zinc-800 rounded-xl space-y-4">
            <h2 className="text-lg font-semibold text-white flex items-center gap-2">
              <Lightbulb className="h-5 w-5 text-amber-400" /> Hypotheses
            </h2>
            <ul className="space-y-3">
              {(reasoning.hypotheses || []).map((hyp, idx) => (
                <li key={idx} className="p-3 bg-zinc-950 border border-zinc-800/50 rounded-lg text-sm text-zinc-300">
                  {hyp}
                </li>
              ))}
            </ul>
          </div>

          <div className="p-6 bg-zinc-900/50 border border-zinc-800 rounded-xl space-y-4">
            <h2 className="text-lg font-semibold text-white flex items-center gap-2">
              <Target className="h-5 w-5 text-purple-400" /> Recommended Actions
            </h2>
            <div className="space-y-3">
              {(reasoning.recommended_actions || []).map((action, idx) => (
                <div key={idx} className="p-4 bg-zinc-950 border border-purple-900/30 rounded-lg">
                  <div className="flex justify-between items-start mb-2">
                    <span className="text-sm font-bold text-white capitalize">{action.action_type.replace('_', ' ')}</span>
                    <span className="text-xs font-mono px-2 py-1 bg-zinc-900 rounded text-purple-400 border border-zinc-800">
                      Target: {action.target}
                    </span>
                  </div>
                  <p className="text-sm text-zinc-400 mb-2">{action.description}</p>
                  <p className="text-xs text-zinc-500 mt-2 border-t border-zinc-800/50 pt-2">
                    <strong>Expected:</strong> {action.expected_outcome}
                  </p>
                </div>
              ))}
            </div>
            {(reasoning.recommended_actions || []).length > 0 && (
              <div className="mt-4 pt-4 border-t border-zinc-800 flex justify-end">
                <Link href="/recovery" className="text-sm font-medium text-blue-400 hover:text-blue-300">
                  Generate Recovery Plan →
                </Link>
              </div>
            )}
          </div>

          <div className="p-6 bg-red-950/20 border border-red-900/30 rounded-xl space-y-4">
            <h2 className="text-lg font-semibold text-red-400 flex items-center gap-2">
              <AlertTriangle className="h-5 w-5" /> Uncertainty Factors
            </h2>
            <ul className="space-y-2">
              {(reasoning.uncertainty_factors || []).map((unc, idx) => (
                <li key={idx} className="flex items-start gap-2 text-sm text-red-300">
                  <div className="min-w-1.5 h-1.5 rounded-full bg-red-500 mt-1.5" />
                  {unc}
                </li>
              ))}
              {(reasoning.uncertainty_factors || []).length === 0 && (
                <li className="text-sm text-zinc-500 italic">None reported.</li>
              )}
            </ul>
          </div>
        </div>

      </div>
    </div>
  );
}
